<?php

namespace AppBundle\Repository;

/**
 * CaseappRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseAppRepository extends \Doctrine\ORM\EntityRepository
{
}
