<?php

namespace AppBundle\Repository;

/**
 * FriendLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
