<?php

namespace AppBundle\Repository;

/**
 * SiteBuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteBuildRepository extends \Doctrine\ORM\EntityRepository
{
}
