<?php

namespace AppBundle\Repository;

/**
 * SittingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SittingsRepository extends \Doctrine\ORM\EntityRepository
{
}
