<?php

namespace AppBundle\Repository;

/**
 * SwiperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwiperRepository extends \Doctrine\ORM\EntityRepository
{
}
