<?php

namespace AppBundle\Repository;

/**
 * VisitedLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedLogRepository extends \Doctrine\ORM\EntityRepository
{
}
