easy_admin:
    entities:
        Article:
            label: '文章管理'
            class: 'AppBundle\Entity\Article'
            form:
                fields:
                    - { property: title, label: '标题' }
                    - { property: summary, label: '简介' }
                    - { property: imageFile, label: '预览图片', type: vich_image }
                    - { property: content, label: '文章内容', type: ckeditor, type_options: { config_name: advanced_config} }
                    - { property: categories, label: '所属分类', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Category'} }
                    - { property: keywords, label: '关键词'  }
                    - { property: description, label: '页面描述' }
            list:
                title: '文章列表'
                fields:
                    - { property: id, label: '编号'}
                    - { property: image, label: '图片', type: image, base_path: "%app.path.article_images%"}
                    - { property: title, label: '标题'}
                    - { property: summary, label: '简介'}
                    - { property: content, label: '内容'}
                    - { property: createdAt, label: '发布时间'}
                    - { property: author, label: '作者'}