easy_admin:
    entities:
        Article:
            label: '文章管理'
            class: 'AppBundle\Entity\Article'
            form:
                fields:
                    - { property: title, label: '标题' }
                    - { property: summary, label: '简介' }
                    - { property: titlePic, label: '预览图片' }
                    - { property: content, label: '文章内容' }
                    - { property: categories, type: 'AppBundle\Form\Type\CategoryType' }
            list:
                title: '文章列表'
                fields:
                    - { property: id, label: '编号'}
                    - { property: title, label: '标题'}
                    - { property: summary, label: '简介'}
                    - { property: content, label: '内容'}
                    - { property: createdAt, label: '发布时间'}
                    - { property: author, label: '作者'}